"use strict";

export const CONFIG = {
	// Particle grid
	SPACING_MOBILE: 5.0,
	SPACING_DESKTOP: 8.0,
	COLOR: 220,

	// Particle physics
	PARTICLE_DRAG: 0.92,
	PARTICLE_EASE: 0.35,
	REPULSION_RADIUS: 80,
	REPULSION_STRENGTH: 1.0,
	SPIRAL_STRENGTH_BASE: 0.3,
	SPIRAL_TIGHTENING_RATE: 0.00015,

	// Cursor movement
	CURSOR_PATH_SPEED_MIN: 100,
	CURSOR_PATH_SPEED_MAX: 155,
	CURSOR_PATH_RADIUS: 0.45,
	CURSOR_SPEED_DURATION: 30000,
	CURSOR_SPRING: 0.35,
	CURSOR_DAMPING: 0.7,
	MANUAL_TIMEOUT: 2000,

	// Growth animation
	GROWTH_DURATION: 180000, // 3 minutes
	GROWTH_START_RADIUS: 0.08,

	// Virus outbreaks
	OUTBREAK_SPAWN_MIN: 35000,
	OUTBREAK_SPAWN_MAX: 18000,
	OUTBREAK_SPAWN_MIN_MOBILE: 40000,
	OUTBREAK_SPAWN_MAX_MOBILE: 22000,
	OUTBREAK_GROWTH_RATE: 0.4,
	OUTBREAK_GROWTH_RATE_MOBILE: 0.35,
	OUTBREAK_MAX_RADIUS: 140,
	OUTBREAK_MAX_RADIUS_MOBILE: 120,
	OUTBREAK_KILL_RADIUS: 50,
	OUTBREAK_DAMAGE_RADIUS: 100,
	OUTBREAK_DISSOLVE_RADIUS: 25,
	OUTBREAK_PULL_RADIUS_MIN: 0.5, // Start pulling at 50% of virus size
	OUTBREAK_PULL_RADIUS_MAX: 2.0, // Can pull up to 2.0x virus size (reduced from 2.5)

	// Anomalies
	ANOMALY_SPAWN_MIN: 12000,
	ANOMALY_SPAWN_MAX: 20000,
	ANOMALY_SPAWN_MIN_MOBILE: 25000,
	ANOMALY_SPAWN_MAX_MOBILE: 40000,
	ANOMALY_ORBIT_RADIUS: 40,
	ANOMALY_ORBIT_SPEED: 0.02,
	ANOMALY_DRIFT_SPEED: 0.3,
	ANOMALY_VORTEX_RADIUS: 60,
	ANOMALY_VORTEX_STRENGTH: 0.8,
	ANOMALY_DISSOLVE_RADIUS: 20,

	// Energy Stations
	STATION_SPAWN_MIN: 30000,
	STATION_SPAWN_MAX: 60000,
	STATION_DRIFT_SPEED: 0.15,
	STATION_CAPTURE_RADIUS: 35,
	STATION_LIFETIME: 75000, // 75 seconds before despawn

	// Synergy between anomalies and viruses
	SYNERGY_RANGE: 100, // Distance for synergy effects
	SYNERGY_VORTEX_BOOST: 1.6, // Anomaly vortex becomes much stronger near virus
	SYNERGY_GROWTH_BOOST: 1.8, // Virus grows faster near anomaly
	SYNERGY_REGEN_BOOST: 3.0, // Virus regenerates faster near anomaly
	SYNERGY_PROTECTION: 0.5, // Virus takes less damage near anomaly
};
